TrajectoryPlannerROS:
  max_vel_x: 0.20
  min_vel_x: 0.20
  max_vel_theta: 1.5
  min_vel_theta: 0.8
  min_in_place_vel_theta: 0.8

  acc_lim_x: 180
  acc_lim_y: 0.0
  acc_lim_th: 620

  holonomic_robot: false
