footprint: [ [0.22, 0.11], [-0.08, 0.11], [-0.08, -0.11], [0.22, -0.11] ]
#robot_radius: 0.15
inflation_radius: 0.55

obstacle_layer:
  observation_sources: laser_scan_sensor
  obstacle_range: 2.5
  raytrace_range: 3.0
  laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
